title: Student 2.0
description: "November 2023 to March 2024"
owner_name: Matthew Sean Borabo
github_username: MatthewBorabo
github_repo: "student2.0"
baseurl: "/student2.0"
future: true
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/MatthewBorabo/teacher_portfolio"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" }      
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/search.html


